global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'ticket-system'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - '/etc/prometheus/rules.yml'

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (métricas del sistema)
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']

  # MySQL Exporter (métricas de la BD)
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql_exporter:9104']

  # Pushgateway (métricas empujadas por los test)
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']
